### ISSUE TITLE
Upgrade lambda runtime to use NODEJS_10 instead of 8

### ISSUE THREAD

**Issue by iliapolo** [awslabs/aws-delivlib#220]

**Comment by skinny85** [comment]
I'm working on it.

**Comment by hnishar** [comment]
Upgrading to Node 10_X throws the following error when the lambda based custom resource is attempting to execute 'gpg' commands:

ERROR	{ Error: spawn gpg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn gpg',
  path: 'gpg',
  spawnargs: [ '--batch', '--gen-key', '/tmp/OpenPGP-8X0IF1/key.config' ] }

**Comment by skinny85** [comment]
@hnishar see: https://github.com/awslabs/aws-delivlib/pull/226
