### ISSUE TITLE
working end-to-end example

### ISSUE THREAD

**Issue by ahammond** [awslabs/aws-delivlib#228]
A working, end-to-end example would be an enormous help. I assume that delivlib is self-hosting? If so, then the cdk used to deploy it would be a perfect example.

**Comment by skinny85** [comment]
@ahammond does this help? https://github.com/awslabs/aws-delivlib/blob/c3eca8f22924fe7b29a2252f5f19ef6d2039781a/pipeline/delivlib.ts#L13

**Comment by ahammond** [comment]
@skinny85 this is everything I dreamed it could be and more! Maybe throw a link in the docs? I also found https://garbe.io/blog/2019/03/26/construct-your-own-cdk-construct-library/ which seems relevant.

**Comment by skinny85** [comment]
> @skinny85 this is everything I dreamed it could be and more! Maybe throw a link in the docs? I also found https://garbe.io/blog/2019/03/26/construct-your-own-cdk-construct-library/ which seems relevant.

Agreed! Done in: https://github.com/awslabs/aws-delivlib/pull/235 , let me know if this is what you had in mind @ahammond .
