### ISSUE TITLE
AutoPR's do not work in pipelines if your repo does not have a branch named 'master'

### ISSUE THREAD

**Issue by grbartel** [awslabs/aws-delivlib#450]
The code for the auto PR's currently have a hard coded call to  `git reset --hard master` that is used when the git repository is not already synced.  Due to this it fails on this line if you do not have a branch named master.  With some repositories changing their naming to 'mainline' instead of master this can cause issues.

Instead of calling `git reset --hard master` it should probably instead call 'git reset --hard ${head.source}'

**Comment by iliapolo** [comment]
Fixed by #451
